; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Thu May 02 2019 10:56:02 GMT-0500 (Central Daylight Time)

