; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Thu May 02 2019 10:56:02 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0

